name       : python-html5lib
version    : 1.0.1
release    : 8
source     :
    - https://github.com/html5lib/html5lib-python/archive/1.0.1.tar.gz : fabbebd6a55d07842087f13849076eeed350aa8bb6c9ec840f6a6aba9388db06
homepage   : https://github.com/html5lib/html5lib-python
license    : MIT
component  : programming.python
summary    : html5lib is a pure-python library for parsing HTML.
description: |
    html5lib is a pure-python library for parsing HTML.
builddeps  :
    - pkgconfig(python3)
rundeps    :
    - python-six
    - python-webencodings
setup      : |
    %python3_setup
install    : |
    %python3_install
