name       : python-html5lib
version    : '0.999999999'
release    : 4
source     :
    - https://github.com/html5lib/html5lib-python/archive/0.999999999.tar.gz : 05c0f1ba235776060ded5093c365483d50deacdd7cabc57b6996d6e2480a4626
license    : MIT
component  : programming.python
summary    : html5lib is a pure-python library for parsing HTML.
description: |
    html5lib is a pure-python library for parsing HTML.
builddeps  :
    - pkgconfig(python-3.5)
    - python-setuptools
rundeps    :
    - python-six
    - python-webencodings
setup      : |
    %python_setup
    %python3_setup
install    : |
    %python_install
    %python3_install
