name       : python-html5lib
version    : 0.9999999
release    : 2
source     :
    - https://github.com/html5lib/html5lib-python/archive/0.9999999.tar.gz : 184257f98539159a433e2a2197309657ae1283b4c44dbd9c87b2f02ff36adce8
license    : MIT
component  : programming.python
summary    : html5lib is a pure-python library for parsing HTML.
description: |
    html5lib is a pure-python library for parsing HTML.
builddeps  :
    - pkgconfig(python-2.7)
    - python-setuptools
    - python-six
rundeps    :
    - python-six
build      : |
    python setup.py build
install    : |
    python setup.py install --root=%installroot% --no-compile -O0
